apiVersion: v1
appVersion: "1.0"
description: This chart is suitable for various type of applications (golang, nodejs, etc...)
name: go-app
version: 1.0.0
home: https://github.com/shurshun/go-app-chart
maintainers:
  - name: Korviakov Andrey
    email: 4lifenet@gmail.com
keywords:
  - helm
  - kubernetes
engine: gotpl
kubeVersion: ">=1.10.0-0"