{{- if .Values.configs }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "go-app.fullname" . }}-configs
  labels:
    app.kubernetes.io/name: {{ include "go-app.name" . }}
    helm.sh/chart: {{ include "go-app.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    addonmanager.kubernetes.io/mode: Reconcile
type: Opaque
data:
{{- range $idx, $cfg := .Values.configs }}
  {{ $cfg.name }}: |-
{{ with $cfg.data }}
{{- if $cfg.format -}}
{{ toJson . | b64enc | indent 4 }}
{{- else -}}
{{ . | b64enc | indent 4 }}
{{- end }}
{{- end }}
{{- end }}
{{- end }}