{{- if .Values.pdb.enabled }}
apiVersion: policy/v1beta1
kind: PodDisruptionBudget
metadata:
  name: {{ include "go-app.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ include "go-app.name" . }}
    helm.sh/chart: {{ include "go-app.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    addonmanager.kubernetes.io/mode: Reconcile
spec:
  maxUnavailable: {{ .Values.pdb.maxUnavailable }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "go-app.name" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
{{- end }}