{{- if .Values.env.secret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "go-app.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ include "go-app.name" . }}
    helm.sh/chart: {{ include "go-app.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    addonmanager.kubernetes.io/mode: Reconcile
type: Opaque
data:
{{- range $key, $value := .Values.env.secret }}
  {{ $key }}: {{ $value | toString | b64enc | quote }}
{{- end }}
{{- end }}