name: CI
on: [push]
jobs:
  helm:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repo
      uses: actions/checkout@v2
    - name: Lint chart
      shell: bash
      env:
        HELM_VERSION: v3.2.3
      run: |
        wget --no-verbose "https://get.helm.sh/helm-${HELM_VERSION}-linux-amd64.tar.gz" -O - | tar -zx -O linux-amd64/helm > helm
        chmod +x helm

        ./helm lint .
